# Generated by Django 5.2.4 on 2025-09-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingest", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scannedcheck",
            name="linked_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanned_check",
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="payoree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.payoree",
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["status"], name="ingest_impo_status_0c60fa_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["created_at"], name="ingest_impo_created_77c45f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["profile"], name="ingest_impo_profile_c9a2da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["batch", "row_index"], name="ingest_impo_batch_i_32e8e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["is_duplicate"], name="ingest_impo_is_dupl_0198d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["norm_date"], name="ingest_impo_norm_da_db7ddb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["batch", "committed_txn_id"],
                name="ingest_impo_batch_i_c72bd4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_index"), name="uniq_batch_rowid"
            ),
        ),
        migrations.AddConstraint(
            model_name="scannedcheck",
            constraint=models.UniqueConstraint(
                fields=("content_md5",), name="unique_scannedcheck_md5"
            ),
        ),
    ]
