# Generated by Django 5.2.4 on 2025-08-11 22:19

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='importrow',
            options={'ordering': ['row_index']},
        ),
        migrations.AddField(
            model_name='importrow',
            name='committed_txn_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='importrow',
            name='parsed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='norm_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='row_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status'], name='ingest_impo_status_0c60fa_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['created_at'], name='ingest_impo_created_77c45f_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['profile'], name='ingest_impo_profile_c9a2da_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['is_duplicate'], name='ingest_impo_is_dupl_0198d9_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['norm_date'], name='ingest_impo_norm_da_db7ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'committed_txn_id'], name='ingest_impo_batch_i_c72bd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_index'), name='uniq_batch_rowidx'),
        ),
    ]
