# Generated by Django 5.2.4 on 2025-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_alter_importbatch_options_alter_importrow_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="MappingProfile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
