# Generated by Django 5.2.4 on 2025-08-26 18:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0004_scannedcheck"),
        ("transactions", "0011_add_payoree_to_keyword_rules"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="importrow",
            name="uniq_batch_rowidx",
        ),
        migrations.RemoveField(
            model_name="scannedcheck",
            name="matched_transaction",
        ),
        migrations.RemoveField(
            model_name="scannedcheck",
            name="memo_text",
        ),
        migrations.RemoveField(
            model_name="scannedcheck",
            name="payee_text",
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="content_md5",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="memotext",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="original_filename",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="payoree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.payoree",
            ),
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanned_checks",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="scannedcheck",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="scannedcheck",
            name="bank_account",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="scannedcheck",
            name="check_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_index"), name="uniq_batch_rowid"
            ),
        ),
    ]
