# Generated by Django 5.2.4 on 2025-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0005_remove_importrow_uniq_batch_rowidx_and_more"),
        ("transactions", "0011_add_payoree_to_keyword_rules"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scannedcheck",
            constraint=models.UniqueConstraint(
                fields=("content_md5",), name="unique_scannedcheck_md5"
            ),
        ),
    ]
