# Generated by Django 5.2.4 on 2025-08-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0006_scannedcheck_unique_scannedcheck_md5"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scannedcheck",
            old_name="memotext",
            new_name="memo_text",
        ),
    ]
