# Generated by Django 5.2.4 on 2025-08-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0007_rename_memotext_scannedcheck_memo_text"),
        ("transactions", "0011_add_payoree_to_keyword_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scannedcheck",
            name="transaction",
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="linked_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanned_check",
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("unmatched", "Unmatched"),
                    ("matched", "Matched"),
                    ("confirmed", "Confirmed"),
                ],
                default="unmatched",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scannedcheck",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
