# Generated by Django 5.2.4 on 2025-08-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0008_remove_scannedcheck_transaction_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MappingProfile",
            new_name="FinancialAccount",
        ),
    ]
