# Generated by Django 5.2.4 on 2025-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0010_convert_scannedcheck_bank_account_to_foreignkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scannedcheck",
            name="bank_account",
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
