# Generated by Django 5.2.4 on 2025-09-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoree",
            name="default_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Default category for this payoree",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payoree_default_categories",
                to="transactions.category",
            ),
        ),
        migrations.AddField(
            model_name="payoree",
            name="default_subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="Default subcategory for this payoree",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payoree_default_subcategories",
                to="transactions.category",
            ),
        ),
    ]
