# Generated by Django 5.2.4 on 2025-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'amount', 'description', 'bank_account'], name='transaction_date_c0566d_idx'),
        ),
    ]
