# Generated by Django 5.2.4 on 2025-08-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_tag_transaction_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedPayoree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateField(auto_now=True)),
                ('payoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.payoree')),
            ],
            options={
                'unique_together': {('key', 'payoree')},
            },
        ),
        migrations.CreateModel(
            name='LearnedSubcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category')),
            ],
            options={
                'unique_together': {('key', 'subcategory')},
            },
        ),
    ]
