# Generated by Django 5.2.4 on 2025-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_payoree_default_category_payoree_default_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringseries",
            name="manually_disabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this series has been manually marked as non-recurring by user",
            ),
        ),
    ]
