# Generated by Django 5.2.4 on 2025-08-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_date_c0566d_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('date', 'amount', 'description', 'bank_account'), name='unique_transaction'),
        ),
    ]
