# Generated by Django 5.2.4 on 2025-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity')], default='expense', max_length=30),
        ),
    ]
