# Generated by Django 5.2.4 on 2025-09-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_add_manually_disabled_to_recurring_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="needs_level",
            field=models.JSONField(
                blank=True,
                help_text="Single value (e.g., {'core': 100}) or percentage allocation across budget tiers",
                null=True,
            ),
        ),
    ]
