# Generated by Django 5.2.4 on 2025-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payoree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='transaction_name_37acd9_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_payoree')],
            },
        ),
    ]
