# Generated by Django 5.2.4 on 2025-08-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_learnedpayoree_learnedsubcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categorization_error',
            field=models.CharField(blank=True, help_text='Describes why subcategory/payoree assignment failed', max_length=200, null=True),
        ),
    ]
