# Generated by Django 5.2.4 on 2025-08-15 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_categorization_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_in_category', to='transactions.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional subcategory - must belong to the specified category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_in_subcategory', to='transactions.category'),
        ),
    ]
