# Generated by Django 5.2.4 on 2025-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_add_needs_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoree",
            name="default_needs_level",
            field=models.JSONField(
                blank=True,
                help_text="Default needs level for this payoree (e.g., {'discretionary': 100})",
                null=True,
            ),
        ),
    ]
