# Generated by Django 5.2.4 on 2025-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_payoree'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payoree',
            name='unique_payoree',
        ),
        migrations.RemoveIndex(
            model_name='payoree',
            name='transaction_name_37acd9_idx',
        ),
    ]
