# Generated by Django 5.2.4 on 2025-08-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_payoree_unique_payoree_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payoree',
            index=models.Index(fields=['name'], name='transaction_name_37acd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoree',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_payoree'),
        ),
    ]
