# Generated by Django 5.2.4 on 2025-09-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_add_default_needs_level_to_payoree"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE transactions_payoree SET default_needs_level = '{\"discretionary\": 100}' WHERE default_needs_level IS NULL OR default_needs_level = 'null' OR default_needs_level = '{}'",
            reverse_sql="UPDATE transactions_payoree SET default_needs_level = NULL WHERE default_needs_level = '{\"discretionary\": 100}'",
        )
    ]
