# Generated by Django 5.2.4 on 2025-08-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_payoree_transaction_name_37acd9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payoree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.payoree'),
        ),
    ]
