# Generated by Django 5.2.4 on 2025-08-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_populate_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=134, help_text='Primary category for this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions_in_category', to='transactions.category'),
            preserve_default=False,
        ),
    ]
