# Generated by Django 5.2.4 on 2025-08-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_make_category_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category for this transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_in_category', to='transactions.category'),
        ),
    ]
