# Generated by Django 5.2.4 on 2025-08-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_category_not_null_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Word or phrase that influences categorization', max_length=100)),
                ('priority', models.IntegerField(default=100, help_text='Higher numbers = higher priority (1-1000)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.BooleanField(default=True, help_text='True if created by user, False if system default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='transactions.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_subcategory_rules', to='transactions.category')),
            ],
            options={
                'ordering': ['-priority', 'keyword'],
                'indexes': [models.Index(fields=['keyword'], name='kw_rule_keyword_idx'), models.Index(fields=['priority'], name='kw_rule_priority_idx'), models.Index(fields=['is_active'], name='kw_rule_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('keyword', 'category', 'subcategory'), name='unique_keyword_category')],
            },
        ),
    ]
