# Generated by Django 5.2.4 on 2025-08-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_keywordrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedSimilarTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_at', models.DateTimeField(auto_now_add=True)),
                ('excluded_transaction', models.ForeignKey(help_text='The similar transaction to exclude', on_delete=django.db.models.deletion.CASCADE, related_name='excluded_similar_target', to='transactions.transaction')),
                ('source_transaction', models.ForeignKey(help_text='The transaction being resolved', on_delete=django.db.models.deletion.CASCADE, related_name='excluded_similar_source', to='transactions.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['source_transaction'], name='excl_sim_source_idx'), models.Index(fields=['excluded_transaction'], name='excl_sim_target_idx')],
                'unique_together': {('source_transaction', 'excluded_transaction')},
            },
        ),
    ]
