# Generated by Django 5.2.4 on 2025-08-21 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_excludedsimilartransaction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordrule',
            name='unique_keyword_category',
        ),
        migrations.AddField(
            model_name='keywordrule',
            name='payoree',
            field=models.ForeignKey(blank=True, help_text='Optional: Assign specific payoree for this keyword', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='transactions.payoree'),
        ),
        migrations.AddConstraint(
            model_name='keywordrule',
            constraint=models.UniqueConstraint(fields=('keyword', 'category', 'subcategory', 'payoree'), name='unique_keyword_rule'),
        ),
    ]
