# Generated by Django 5.2.4 on 2025-08-28 12:35

import django.db.models.deletion
from django.db import migrations, models


def convert_bank_account_data(apps, schema_editor):
    """Convert string bank_account values to ForeignKey IDs."""
    Transaction = apps.get_model("transactions", "Transaction")
    FinancialAccount = apps.get_model("ingest", "FinancialAccount")

    # Get the FinancialAccount records
    chase_account = FinancialAccount.objects.get(name="Chase Checking 3607")
    marriott_account = FinancialAccount.objects.get(name="Marriott Visa 7427")

    # Update Transaction records
    Transaction.objects.filter(bank_account="Chase Checking 3607").update(
        bank_account=chase_account.id
    )
    Transaction.objects.filter(bank_account="Marriott Visa 7427").update(
        bank_account=marriott_account.id
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0011_alter_scannedcheck_bank_account"),
        ("transactions", "0011_add_payoree_to_keyword_rules"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_date_7d5da2_idx",
            old_name="transaction_date_c0566d_idx",
        ),
        migrations.RunPython(
            convert_bank_account_data,
            migrations.RunPython.noop,  # No reverse operation needed
        ),
        migrations.AlterField(
            model_name="transaction",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingest.financialaccount",
            ),
        ),
    ]
