# Generated by Django 5.2.4 on 2025-09-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0012_rename_transaction_date_c0566d_idx_transaction_date_7d5da2_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_cents", models.IntegerField(help_text="Amount in cents")),
                (
                    "amount_tolerance_cents",
                    models.IntegerField(
                        default=100, help_text="Tolerance for amount matching in cents"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="Recurrence interval",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Confidence score for this pattern"
                    ),
                ),
                (
                    "first_seen",
                    models.DateField(
                        blank=True,
                        help_text="Date this pattern was first observed",
                        null=True,
                    ),
                ),
                (
                    "last_seen",
                    models.DateField(
                        blank=True,
                        help_text="Date this pattern was last observed",
                        null=True,
                    ),
                ),
                (
                    "next_due",
                    models.DateField(
                        blank=True, help_text="Next expected occurrence", null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether this series is still active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about this series",
                    ),
                ),
                (
                    "payoree",
                    models.ForeignKey(
                        blank=True,
                        help_text="The payoree for this recurring series",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.payoree",
                    ),
                ),
                (
                    "seed_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The transaction that seeded this series",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seeded_series",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["payoree", "amount_cents"],
                        name="recurring_payoree_amount_idx",
                    ),
                    models.Index(fields=["next_due"], name="recurring_next_due_idx"),
                    models.Index(fields=["active"], name="recurring_active_idx"),
                ],
            },
        ),
    ]
