# Generated by Django 5.2.4 on 2025-08-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0013_add_recurringseries"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recurringseries",
            new_name="transaction_merchan_6175ab_idx",
            old_name="transactions_recurring_merchant_amount_idx",
        ),
        migrations.RenameIndex(
            model_name="recurringseries",
            new_name="transaction_next_du_3ee9f9_idx",
            old_name="transactions_recurring_next_due_idx",
        ),
        migrations.RenameIndex(
            model_name="recurringseries",
            new_name="transaction_active_fcc8ae_idx",
            old_name="transactions_recurring_active_idx",
        ),
    ]
