# Generated by Django 5.2.4 on 2025-09-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0013_recurringseries"),
    ]

    operations = []
