# Generated by Django 5.2.4 on 2025-09-21 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0006_set_default_needs_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "total_budgeted",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "baseline_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="True when user has finalized this budget period",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Period-level notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="budgets_bud_year_60e932_idx"
                    ),
                    models.Index(
                        fields=["is_finalized"], name="budgets_bud_is_fina_fb6434_idx"
                    ),
                ],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "needs_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("core", "Core"),
                            ("lifestyle", "Lifestyle"),
                            ("discretionary", "Discretionary"),
                            ("luxury", "Luxury"),
                            ("deferred", "Deferred"),
                        ],
                        help_text="Budget applies to this needs level",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly budget amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "is_ai_suggested",
                    models.BooleanField(
                        default=False,
                        help_text="True if this budget was auto-populated by AI",
                    ),
                ),
                (
                    "baseline_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Historical baseline used for AI suggestion",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("user_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget applies to this category",
                        limit_choices_to={"parent__isnull": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.category",
                    ),
                ),
                (
                    "payoree",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget applies to this payoree",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.payoree",
                    ),
                ),
                (
                    "recurring_series",
                    models.ForeignKey(
                        blank=True,
                        help_text="Connected recurring transaction series",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.recurringseries",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget applies to this subcategory",
                        limit_choices_to={"parent__isnull": False},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategory_budgets",
                        to="transactions.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "category__name"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="budgets_bud_year_d841e3_idx"
                    ),
                    models.Index(
                        fields=["category"], name="budgets_bud_categor_aa2cf8_idx"
                    ),
                    models.Index(
                        fields=["needs_level"], name="budgets_bud_needs_l_5413e7_idx"
                    ),
                    models.Index(
                        fields=["recurring_series"],
                        name="budgets_bud_recurri_c56546_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "year",
                        "month",
                        "category",
                        "subcategory",
                        "payoree",
                        "needs_level",
                    )
                },
            },
        ),
    ]
