# Generated by Django 5.2.4 on 2025-09-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monthly budget amount (positive for income, negative for expenses)",
                max_digits=12,
            ),
        ),
    ]
